spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: 1899
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
